### ISSUE TITLE
Idea: Switch to using RFC3339 for DateTime format

### ISSUE THREAD

**Issue by ajvb** [elimisteve/cryptag#45]
In the `TimeStr` (https://github.com/elimisteve/cryptag/blob/master/time.go#L19-L23), the datetime format is compacted RFC3339 without separators and a timezone.

```
"20060102150405" vs "2006-01-02T15:04:05Z07:00"
```

In my experiences with using timestamp data, at some point I am really sad I am lacking a timezone, and generally go to feeling that I with I had used RFC 3339 always synced to UTC.

I wanted to create an issue before submitting a PR as this is a breaking change, and am not sure of the current test coverage through out the code base.

**Comment by ajvb** [comment]
Also, as an added benefit, you get to use `mytime.Format(time.RFC3339)` and get to delete code. :)

**Comment by elimisteve** [comment]
@ajvb All times are UTC, so there's no functionality lacking from not having an _apparent_ timezone. And whatever the format, times in that format must be in lexicographical order (for efficiency reasons, specifically sorting `*Row`s by `created:...` without having to parse those strings into `time.Time` objects.)
